---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: docserver
  namespace: longhorn-system
spec:
  allowScheduling: true
  disks:
    hdd-2:
      path: /var/lib/longhorn
      diskType: filesystem
      allowScheduling: true
      tags: ["hdd", "raid0"]
