---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: ds-node3
  namespace: longhorn-system
spec:
  allowScheduling: true
  disks:
    hdd-1:
      path: /mnt/longhorn
      allowScheduling: true
      tags: ["hdd", "raid0"]