apiVersion: v1
kind: Service
metadata:
  name: longhorn-ui-nodeport
  namespace: longhorn-system
spec:
  type: NodePort
  selector:
    app: longhorn-ui
  ports:
    - name: http
      port: 80                  
      targetPort: 8000
      protocol: TCP
      nodePort: 30081           
