---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: db-init
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/Andrej220/HAM-core-services
    targetRevision: HEAD
    path: manifests/db-init
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
