apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-password-update
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: mongodb
    targetRevision: 16.4.12
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/Andrej220/HAM-core-services/HEAD/applications/mongodb-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: database-test
  syncPolicy:
    automated: {}