# architecture: "replicaset"
# replicaCount: 2
auth:
  rootUser: "root"
  rootPassword: "password"
  usernames: ["appuser"]
  passwords: ["apppassword"]
  databases: ["appdb"]

passwordUpdateJob:
  enabled: false
  existingSecret: mongodb
  existingSecretKey: mongodb-password
previousPasswords:
  existingSecret: mongodb
podAnnotations:
  "argocd.argoproj.io/hook": "PostSync"  
  "argocd.argoproj.io/hook-delete-policy": "HookSucceeded"

fullnameOverride: "mongodb"
nameOverride: "mongodb"
podLabels:
  app: mongodb
persistence:
  enabled: true
  existingClaim: mongodb-data
  storageClass: raid10-storage   
nodeSelector:
    kubernetes.io/hostname: ds-node1 