---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: database-test
stringData:
  mongodb-root-password: password
  mongodb-usernames:  '["appuser"]'
  mongodb-passwords:  '["apppassword"]'
  mongodb-databases:  '["appdb"]'
type: Opaque

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: mongodb
    targetRevision: 16.4.12
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/Andrej220/HAM-core-services/main/applications/mongodb-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: database-test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
