---
apiVersion: v1
kind: ConfigMap
metadata:
    name: mongodb
    namespace: database-test
data:
    mongodb-usernames: appuser
    mongodb-databases: appdb
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: mongodb
    targetRevision: 16.4.12
    helm:
      #valueFiles:
      #  - https://raw.githubusercontent.com/Andrej220/HAM-core-services/main/applications/mongodb-values.yaml
      values: |
        extraEnvVars:
            - name: GLIBC_TUNABLES
              value: glibc.pthread.rseq=0
        auth:
          enabled: true
          usernames: ["appuser"]
          databases: ["appdb"]
          passwords: []
        fullnameOverride: mongodb
        nameOverride: mongodb
        persistence:
          enabled: true
          existingClaim: mongodb-data
        nodeSelector:
          kubernetes.io/hostname: ds-node1     
  destination:
    server: https://kubernetes.default.svc
    namespace: database-test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
