auth:
  existingSecret: mongodb
  existingSecretKey: mongodb-root-password
  rootPasswordKey: mongodb-root-password
  usernameKey: mongodb-usernames
  passwordKey: mongodb-passwords
  databaseKey: mongodb-databases
  enabled: true
  usernames: 
    - "appuser"
  passwords: 
    - "apppassword"
  databases: 
    - "appdb"
  forcePassword: true
fullnameOverride: mongodb
nameOverride: mongodb
persistence:
  enabled: true
  existingClaim: mongodb-datac
nodeSelector:
  kubernetes.io/hostname: ds-node1