architecture: "replicaset"
replicaCount: 2
auth:
  rootUser: "root"
  rootPassword: "password"
  usernames: ["appuser"]
  passwords: ["apppassword"]
  databases: ["appdb"]

passwordUpdateJob:
  enabled: true
  previousPasswords:
    existingSecret: mongodb

persistence:
  storageClass: raid10-storage
  size: 10Gi

annotations:
  argocd.argoproj.io/sync-wave: "2"  