architecture: "replicaset"
replicaCount: 2
auth:
  rootPassword: password
  username: appuser
  password: apppassword
  database: appdb

passwordUpdateJob:
  enabled: true
  previousPasswords:
    existingSecret: previous-password-secret

persistence:
  storageClass: raid10-storage
  size: 10Gi