auth:
  enabled: true
  rootPassword: rootpassword
  username: appuser
  password: apppassword
  database: appdb
fullnameOverride: mongodb
nameOverride: mongodb
persistence:
  enabled: true
  existingClaim: mongodb-data
nodeSelector:
  kubernetes.io/hostname: ds-node1