auth:
  enabled: true
  rootPassword: rootpassword
  usernames: 
    - appuser
  passwords: 
    - apppassword
  databases: 
    - appdb
fullnameOverride: mongodb
nameOverride: mongodb
persistence:
  enabled: true
  existingClaim: mongodb-data
nodeSelector:
  kubernetes.io/hostname: ds-node1