auth:
  enabled: true
  usernames: 
    - "appuser"
  passwords: 
    - "apppassword"
  databases: 
    - "appdb"
  forcePassword: true
fullnameOverride: mongodb
nameOverride: mongodb
persistence:
  enabled: true
  existingClaim: mongodb-data
nodeSelector:
  kubernetes.io/hostname: ds-node1