persistence:
    storageClass: ""
    existingClaim: postgres-data  
    enabled: true 
primary:
  persistence:
    existingClaim: postgres-data  
    
podManagementPolicy: OrderedReady
persistentVolumeClaimRetentionPolicy:  
  whenDeleted: Retain
  whenScaled: Retain
nodeSelector:
    kubernetes.io/hostname: ds-node1 