---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.8
    helm:
      parameters:
          - name: auth.postgresPassword
            valueFrom:
              secretKeyRef:
                name: app-credentials
                key: postgres-password
          - name: auth.password
            valueFrom:
              secretKeyRef:
                name: app-credentials
                key: postgresUserPassword
          - name: auth.username
            valueFrom:
              secretKeyRef:
                name: app-credentials
                key: postgresUsername
      values: |
          auth:
            enabled: true
            postgresPassword: ""
            postgresqlDatabase: "appdb"
            username: ""  
            password: ""
            forcePassword: true  
      valueFiles:
        - https://raw.githubusercontent.com/Andrej220/HAM-core-services/main/applications/postgresql-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: database-test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
