---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 15.5.8
    helm:
      values: |
        auth:
          enabled: true
          database: "appdb"
          username: "appuser"  
          password: ""  
          forcePassword: true
        fullnameOverride: "postgresql"
        nameOverride: "postgresql"
        podLabels:
          app: postgresql
        persistence:
          storageClass: ""
          existingClaim: postgres-data
          enabled: true
        primary:
          persistence:
            existingClaim: postgres-data
        podManagementPolicy: OrderedReady
        persistentVolumeClaimRetentionPolicy:
          whenDeleted: Retain
          whenScaled: Retain
        nodeSelector:
          kubernetes.io/hostname: ds-node1
        tls:
          enabled: truecc 
          autoGenerated: true
      #valueFiles:
      #  - https://raw.githubusercontent.com/Andrej220/HAM-core-services/main/applications/postgresql-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
