apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-data
  namespace: database
  labels:
    app: mongodb
    chart: mongodb-12.1.0
    release: mongodb
    heritage: Helm
spec:
  storageClassName: raid10-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-raid10-mongodb