apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: database
  labels:
    app: postgres
    chart: postgresql-15.5.8
    release: postgresql
    heritage: Helm
spec:
  storageClassName: raid10-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-raid10-postgresql