---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: raid10-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-raid10
spec:
  capacity:
    storage: 900Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: raid10-storage
  local:
    path: /mnt/raid10
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ds-node1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-raid10-mongo
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: raid10-storage
  local:
    path: /mnt/raid10/mongo
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ds-node1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-raid10-postgresql  # New PV for PostgreSQL
spec:
  capacity:
    storage: 10Gi  # Matches the requested size
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: raid10-storage
  local:
    path: /mnt/raid10/postgresql  # Unique path
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ds-node1       