apiVersion: v1
kind: ConfigMap
metadata:
  name: init-mongodb-scripts
  namespace: database-test
data:
  init.py: |

    import os, json
    from pymongo import MongoClient

    users = json.loads(os.getenv("MONGO_USER", "[]"))
    pwds  = json.loads(os.getenv("MONGO_PASS", "[]"))
    dbs   = json.loads(os.getenv("MONGO_DB",   "[]"))

    user = users[0] if users else "root"
    pwd  = pwds[0]  if pwds  else ""
    db   = dbs[0]   if dbs   else "admin"
    print(user, pwd, db)
    # Connect and insert
    mongo = MongoClient(f"mongodb://{user}:{pwd}@mongodb:27017/{db}")
    collection = mongo[db]["host_results"]
    collection.insert_one({
        "system_id": 1,
        "executed_at": datetime.utcnow(),
        "result": { "id": user, "fields": [] }
    })