apiVersion: batch/v1
kind: Job
metadata:
  name: init-mongo-databas
  namespace: database-test
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: init
        image: python:3.10
        command:
          - "sh"
          - "-c"
          - |
            python3 /scripts/init.py
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: postgres-password
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-username
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-password
        - name: MONGO_DB
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: mongodb-database
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: init-mongodb-scripts