apiVersion: v1
kind: ConfigMap
metadata:
  name: init-postgres-scripts
  namespace: database
data:
  init.sql: |
    CREATE TABLE customers (
      id SERIAL PRIMARY KEY,
      name TEXT NOT NULL,
      location TEXT
    );
    CREATE TABLE systems (
      id SERIAL PRIMARY KEY,
      customer_id INTEGER REFERENCES customers(id),
      hostname TEXT,
      ip_address TEXT,
      port INTEGER,
      login TEXT
    );