apiVersion: v1
kind: ConfigMap
metadata:
  name: init-mongodb-scripts
  namespace: database-test
data:
  init.py: |
    from pymongo import MongoClient
    from datetime import datetime
    import os

    mongo = MongoClient(f"mongodb://appuser:{os.environ['MONGO_PASS']}@mongodb:27017/appdb")
    db = mongo['appdb']
    collection = db["host_results"]
    collection.insert_one({
        "system_id": 1,
        "executed_at": datetime.utcnow(),
        "result": {
            "id": "root",
            "fields": []
        }
    })