apiVersion: v1
kind: ConfigMap
metadata:
  name: init-mongodb-scripts
  namespace: database
data:
  init.py: |
        import os, json
        from datetime import datetime
        from pymongo import MongoClient

        def load_list(envkey):
            raw = os.getenv(envkey, "").strip()
            if not raw:
                return []
            if raw.startswith("[") and raw.endswith("]"):
                try:
                    return json.loads(raw)
                except json.JSONDecodeError:
                    print(f"Warning: malformed JSON in {envkey}={raw!r}, treating as flat string")
            return [raw]

        users = load_list("MONGO_USER")
        pwds  = load_list("MONGO_PASS")
        dbs   = load_list("MONGO_DB")

        user = users[0] if users else "root"
        pwd  = pwds[0]  if pwds  else ""
        db   = dbs[0]   if dbs   else "admin"

        print("DEBUG:", user, pwd, db)

        # now connect & init
        mongo = MongoClient(f"mongodb://{user}:{pwd}@mongodb:27017/{db}")
        collection = mongo[db]["host_results"]
        collection.insert_one({
            "system_id": 1,
            "executed_at": datetime.utcnow(),
            "result": { "id": user, "fields": [] }
        })