apiVersion: batch/v1
kind: Job
metadata:
  name: init-databases
  namespace: database-test
spec:
  backoffLimit: 6  
  completions: 1   
  parallelism: 1   
  template:
    spec:
      restartPolicy: Never  
      containers:
      - name: init
        image: python:3.10
        command:
          - "sh"
          - "-c"
          - |
            apt update && apt install -y postgresql-client && \
            pip install psycopg2-binary pymongo && \
            psql -h postgresql -U postgres -d postgres -f /scripts/init.sql && \
            python3 /scripts/init.py
        env:
        - name: PGPASSWORD
          value: "password"  
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: init-scripts  