apiVersion: batch/v1
kind: Job
metadata:
  name: init-postgres-databas
  namespace: database-test
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: init
        image: python:3.10
        command:
          - "sh"
          - "-c"
          - |
            apt update && apt install -y postgresql-client && \
            pip install psycopg2-binary && \
            psql -h postgresql -U postgres -d appdb -f /scripts/init.sql 
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql
              key: postgres-password
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
      volumes:
      - name: script-volume
        configMap:
          name: init-postgres-scripts