apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: database-test
type: Opaque
stringData:
  mongodb-root-password: password
  mongodb-passwords: ["apppassword"]
  mongodb-usernames: ["appuser"]
  mongodb-databases: ["appdb"]
