apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
    - name: broker
      port: 9092
    - name: controller
      port: 9093
  selector:
    app: kafka
