apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: kafka
  name: kafka
  namespace: kafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-headless
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_PROCESS_ROLES
              value: broker,controller
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 0@kafka-0.kafka-headless.kafka.svc.cluster.local:9093,1@kafka-1.kafka-headless.kafka.svc.cluster.local:9093,2@kafka-2.kafka-headless.kafka.svc.cluster.local:9093
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CLUSTER_ID
              value: "5L6g3nShT-eMCtK--X86sw"
          image: apache/kafka:4.0.0
          name: kafka
          ports:
            - containerPort: 9092
              name: broker
            - containerPort: 9093
              name: controller
          volumeMounts:
            - mountPath: /var/lib/kafka/logs0
              name: volume-0
            - mountPath: /var/lib/kafka/logs1
              name: volume-1
          command:
            - /bin/sh
            - -c
            - |
              export KAFKA_BROKER_ID=${KAFKA_BROKER_ID##*-}
              export KAFKA_NODE_ID=$KAFKA_BROKER_ID
              export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-${HOSTNAME}.kafka-headless.kafka.svc.cluster.local:9092
              exec /opt/kafka/bin/kafka-server-start.sh 
  volumeClaimTemplates:
    - metadata:
        name: volume-0
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn-r0
    - metadata:
        name: volume-1
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn-r10