apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: kafka
  name: kafka
  namespace: kafka
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-headless
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - env:
            - name: KAFKA_BROKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_ADVERTISED_LISTENERS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          image: apache/kafka:4.0.0
          name: kafka
          ports:
            - containerPort: 9092
              name: broker
            - containerPort: 9093
              name: controller
          volumeMounts:
            - mountPath: /var/lib/kafka/logs0
              name: volume-0
            - mountPath: /var/lib/kafka/logs1
              name: volume-1
            - mountPath: /opt/kafka/config/kraft
              name: kafka-config
          command:
            - /bin/sh
            - -c
            - |
              export KAFKA_BROKER_ID=${KAFKA_BROKER_ID##*-}
              export KAFKA_NODE_ID=$KAFKA_BROKER_ID
              export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-${KAFKA_BROKER_ID}.kafka-headless.kafka.svc.cluster.local:9092
              exec /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/kraft/server.properties
  volumes:
    - name: kafka-config
      configMap:
        name: kafka-config
  volumeClaimTemplates:
    - metadata:
        name: volume-0
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn-r0
    - metadata:
        name: volume-1
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: longhorn-r10