apiVersion: v1
kind: Service
metadata:
  name: nfs-svc
  namespace: longhorn-system
spec:
  selector:
    app: nfs-server
  ports:
    - name: nfs-tcp
      protocol: TCP
      port: 2049
      targetPort: 2049
    - name: nfs-udp
      protocol: UDP
      port: 2049
      targetPort: 2049
