---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-service-account
  namespace: longhorn-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: longhorn-pre-upgrade
  namespace: longhorn-system
rules:
  - apiGroups: ["longhorn.io"]
    resources: ["settings"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: longhorn-pre-upgrade
  namespace: longhorn-system
subjects:
  - kind: ServiceAccount
    name: longhorn-service-account
    namespace: longhorn-system
roleRef:
  kind: Role
  name: longhorn-pre-upgrade
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: longhorn-engineimage-access
rules:
  - apiGroups: ["longhorn.io"]
    resources: ["engineimages"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: longhorn-engineimage-access-binding
subjects:
  - kind: ServiceAccount
    name: longhorn-service-account
    namespace: longhorn-system
roleRef:
  kind: ClusterRole
  name: longhorn-engineimage-access
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: longhorn-system
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-pod-reader-binding
  namespace: longhorn-system
subjects:
  - kind: ServiceAccount
    name: longhorn-service-account
    namespace: longhorn-system
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
