apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
  namespace: argocd
type: Opaque
stringData:  
  postgres-password: "password" 
  postgresUsername: "appuser"  
  postgresUserPassword: "password"

  appuser-password: your-secure-appuser-password
  mongodb-password: your-secure-mongodb-password
  
