apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/Andrej220/HAM-core-services
    targetRevision: HEAD
    path: manifests/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: database-test  
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
