---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: bitnami/mongodb
    targetRevision: 16.4.12
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/Andrej220/HAM-core-services/HEAD/apps/mongodb/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: database-test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
  dependsOn:
    - name: ham-core
      namespace: argocd